"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Products",
      [
        {
          name: "Diapers",
          price: 15,
          brand: "Pampers",
          description: "Soft and absorbent diapers for newborn babies.",
          SKU: "DIAP001",
          image: 'https://images.unsplash.com/photo-1565762914578-4c94a99e75ad?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Wipes",
          price: 10,
          brand: "Huggies",
          description: "Gentle baby wipes for cleaning delicate skin.",
          SKU: "WIPES002",
          image: 'https://images.unsplash.com/photo-1552308999-5235a8e9a96d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Shampoo",
          price: 8,
          brand: "Johnson's",
          description: "Mild and tear-free shampoo suitable for baby's sensitive scalp.",
          SKU: "SHAMPOO003",
          image: 'https://images.unsplash.com/photo-1571258388463-fa7b6f5cf9a1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Oil",
          price: 12,
          brand: "Johnson's",
          description: "Gentle baby oil for moisturizing delicate skin.",
          SKU: "OIL004",
          image: 'https://images.unsplash.com/photo-1589968718577-96f6a5d0e5c8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Powder",
          price: 7,
          brand: "Johnson's",
          description: "Talc-free baby powder for keeping skin dry and soft.",
          SKU: "POWDER005",
          image: 'https://images.unsplash.com/photo-1542826751-e1b06b244e82?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Lotion",
          price: 9,
          brand: "Johnson's",
          description: "Gentle baby lotion for moisturizing and soothing delicate skin.",
          SKU: "LOTION006",
          image: 'https://images.unsplash.com/photo-1562603817-678b64bfc19a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // Adding more products to make a total of 12
        {
          name: "Baby Bottle",
          price: 5,
          brand: "Avent",
          description: "BPA-free baby bottle for feeding infants.",
          SKU: "BOTTLE007",
          image: 'https://images.unsplash.com/photo-1580606923354-65e677f3f7db?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Bibs",
          price: 3,
          brand: "Gerber",
          description: "Soft and waterproof bibs for keeping baby clean during feeding.",
          SKU: "BIBS008",
          image: 'https://images.unsplash.com/photo-1581354719246-8037a9c3f9e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Monitor",
          price: 50,
          brand: "Motorola",
          description: "Digital baby monitor for keeping an eye on the baby remotely.",
          SKU: "MONITOR009",
          image: 'https://images.unsplash.com/photo-1560678992-7d30bd29b43b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Carrier",
          price: 40,
          brand: "Ergobaby",
          description: "Ergonomic baby carrier for comfortable carrying of infants.",
          SKU: "CARRIER010",
          image: 'https://images.unsplash.com/photo-1590427476033-c1fd4f05ef3e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Teether",
          price: 6,
          brand: "Nuby",
          description: "Soft silicone teether for soothing teething pain in babies.",
          SKU: "TEETHER011",
          image: 'https://images.unsplash.com/photo-1592180258777-b4027f28b232?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Baby Onesies",
          price: 10,
          brand: "Carter's",
          description: "Cotton onesies for keeping baby warm and cozy.",
          SKU: "ONESIES012",
          image: 'https://images.unsplash.com/photo-1561459970-9f9e40c44719?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Products", null, { restartIdentity: true, truncate: true, cascade: true });
  },
};
